.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH completions 1  "completions " 
.SH NAME
completions \- Generate shell completions, writing them to the standard output
.SH SYNOPSIS
\fBcompletions\fR [\fB\-h\fR|\fB\-\-help\fR] <\fISHELL\fR> 
.SH DESCRIPTION
Generate shell completions, writing them to the standard output
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.TP
<\fISHELL\fR>
The shell type to generate completions for
.br

.br
[\fIpossible values: \fRbash, elvish, fish, powershell, zsh]
