.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH check 1  "check " 
.SH NAME
check \- Check hashes against their actual files
.SH SYNOPSIS
\fBcheck\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIFILE\fR> 
.SH DESCRIPTION
Check hashes against their actual files
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.TP
<\fIFILE\fR>
File containing the list of hashes
