.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH manpages 1  "manpages " 
.SH NAME
manpages \- Generate man pages, writing them to the given directory
.SH SYNOPSIS
\fBmanpages\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIDIR\fR> 
.SH DESCRIPTION
Generate man pages, writing them to the given directory
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.TP
<\fIDIR\fR>
Target directory
