[package]
name = "wholesum"
version = "0.2.1"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
license = "AGPL-3.0-only"
include = ["src/**/*", "CHANGELOG.md", "LICENSE", "README.md"]
homepage = "https://github.com/dnaka91/wholesum"
repository = "https://github.com/dnaka91/wholesum"
description = """\
    Wholesome collection of file hashing algorithms all bundled in a single tool. Like sha256sum, \
    b3sum and others, but one: the whole-sum.\
"""

[dependencies]
anyhow = "1.0.52"
blake2 = "0.10.2"
blake3 = { version = "1.3.0", features = ["traits-preview"] }
clap = { version = "3.0.10", features = ["derive"] }
digest = "0.10.1"
fsb = "0.1.0"
gost94 = "0.10.0"
groestl = "0.10.0"
hex = "0.4.3"
md-5 = "0.10.0"
md2 = "0.10.0"
md4 = "0.10.0"
rayon = "1.5.1"
ripemd = "0.1.0"
sha-1 = "0.10.0"
sha2 = "0.10.1"
sha3 = "0.10.0"
shabal = "0.4.0"
sm3 = "0.4.0"
streebog = "0.10.0"
strum = { version = "0.23.0", features = ["derive"] }
tiger = "0.2.0"
whirlpool = "0.10.0"

[profile.release]
lto = true
