[package]
name = "wholesum"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
license = "AGPL-3.0-only"
include = ["src/main.rs", "LICENSE", "README.md"]
homepage = "https://github.com/dnaka91/wholesum"
repository = "https://github.com/dnaka91/wholesum"
description = """\
    Wholesome collection of file hashing algorithms all bundled in a single tool. Like sha256sum, \
    b3sum and others, but one: the whole-sum.\
"""

[dependencies]
anyhow = "1.0.47"
blake2 = "0.9.2"
blake3 = { version = "1.2.0", features = ["traits-preview"] }
clap = { version = "3.0.1", features = ["derive"] }
digest = "0.9.0"
fsb = "0.0.2"
gost94 = "0.9.1"
groestl = "0.9.0"
hex = "0.4.3"
md-5 = "0.9.1"
md2 = "0.9.0"
md4 = "0.9.0"
rayon = "1.5.1"
ripemd160 = "0.9.1"
ripemd256 = "0.1.0"
ripemd320 = "0.9.0"
sha-1 = "0.9.8"
sha2 = "0.9.8"
sha3 = "0.9.1"
shabal = "0.3.0"
sm3 = "0.3.0"
streebog = "0.9.2"
strum = { version = "0.23.0", features = ["derive"] }
tiger = "0.1.0"
whirlpool = "0.9.0"

[profile.release]
lto = true
