[package]
name = "wholesum"
version = "0.2.3"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
license = "AGPL-3.0-only"
include = ["src/**/*", "CHANGELOG.md", "LICENSE", "README.md"]
homepage = "https://github.com/dnaka91/wholesum"
repository = "https://github.com/dnaka91/wholesum"
description = """\
    Wholesome collection of file hashing algorithms all bundled in a single tool. Like sha256sum, \
    b3sum and others, but one: the whole-sum.\
"""

[dependencies]
anyhow = "1.0.57"
blake2 = "0.10.4"
blake3 = { version = "1.3.1", features = ["traits-preview"] }
clap = { version = "3.1.18", features = ["derive"] }
digest = "0.10.3"
fsb = "0.1.1"
gost94 = "0.10.1"
groestl = "0.10.1"
hex = "0.4.3"
md-5 = "0.10.1"
md2 = "0.10.1"
md4 = "0.10.1"
rayon = "1.5.3"
ripemd = "0.1.1"
sha-1 = "0.10.0"
sha2 = "0.10.2"
sha3 = "0.10.1"
shabal = "0.4.1"
sm3 = "0.4.1"
streebog = "0.10.1"
strum = { version = "0.24.0", features = ["derive"] }
tiger = "0.2.1"
whirlpool = "0.10.1"

[profile.release]
lto = true
