[licenses]
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CC0-1.0",
    "MIT",
]
exceptions = [
    { allow = ["AGPL-3.0"], name = "wholesum" },
    { allow = ["Unicode-3.0"], name = "unicode-ident" },
]
