name: CI
on: [pull_request, push]
env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -C debuginfo=0 -D warnings
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Rust
        uses: taiki-e/github-actions/install-rust@main
        with:
          toolchain: stable
      - name: Configure cache
        uses: Swatinem/rust-cache@v1
      - name: Test
        run: cargo test
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Rust (nightly)
        uses: taiki-e/github-actions/install-rust@main
        with:
          toolchain: nightly
          component: rustfmt
      - name: Run rustfmt
        run: cargo fmt -- --check
      - name: Setup Rust (stable)
        uses: taiki-e/github-actions/install-rust@main
        with:
          toolchain: stable
          component: clippy
      - name: Configure cache
        uses: Swatinem/rust-cache@v1
      - name: Run clippy
        run: cargo clippy -- -D warnings
  cargo-deny:
    name: Cargo Deny
    runs-on: ubuntu-latest
    strategy:
      matrix:
        checks:
          - advisories
          - bans licenses sources
    continue-on-error: ${{ matrix.checks == 'advisories' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Check ${{ matrix.checks }}
        uses: EmbarkStudios/cargo-deny-action@v1
        with:
          command: check ${{ matrix.checks }}
